## configurations
spring:
  profiles:
    active: dev
  data:
    rest:
      basePath: /api
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: password
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

flyway:
  url: jdbc:postgresql://localhost:5432/db
  schemas: USER
  user: postgres
  password: password